spring:
  application:
    name: yadro_pcb_task
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema:
  rabbitmq:
    host: localhost
    port:
    username:
    password: